function pass = test_fstr(verbose)

    arguments
        verbose logical = true
    end

    pass = false;

    % variables that the f-strings below read through evalin
    x = [1 2 3]; %#ok<NASGU>
    c = {1, {2, {3}}}; %#ok<NASGU>
    A3 = reshape(1:8, 2, 2, 2); %#ok<NASGU>
    B3 = reshape(1:3, 1, 1, 3); %#ok<NASGU>
    col_char = ['a'; 'b']; %#ok<NASGU>
    tbl = table([1; 2], [3; 4]);

    data = dictionary( ...
        "", "", ...
        "a", "a", ...
        "{}", "", ...
        "{1+1}", "2", ...
        "{{}}", "{}", ...
        "}}", "}", ...
        "{{", "{", ...
        "{{{", "{{", ...
        "}}}", "}}", ...
        "{ { {", "{ { {", ...
        "{ { { } } }", "{0×0 cell}", ...
        "no variable", "no variable", ...
        "{ 1+1 }", "2", ...
        "{ }", "", ...
        "{x(1:2)}", "[1, 2]", ... % a colon inside brackets is not a spec
        "{x(2:end):.1f}", "[2.0, 3.0]", ...
        "{(1:25)}", "[1, 2, 3, 4, 5, ..., 21, 22, 23, 24, 25]", ...
        "{pi:.3f}", "3.142", ...
        "{c{c{1}} + 1}", "2", ...
        "{{{x(1)}}}", "{1}", ...
        "{""a:b""}", "a:b", ... % quoted text hides : and }
        "{'x:}'}", "'x:}'", ...
        "{strlength(""a:}b"")}", "4", ...
        "{num2str(pi, '%.2f')}", "'3.14'", ...
        "{x'}", "[1, 2, 3]", ...
        "50% off", "50% off", ...
        "50%%", "50%", ...
        "a\tb", sprintf("a\tb"), ...
        "{NaN}", "NaN", ...
        "{[1 NaN]}", "[1, NaN]", ...
        "{[1 2; 3 4]}", sprintf("[[1, 2],\n [3, 4]]"), ...
        "{A3}", sprintf("[[[1, 5],\n  [3, 7]],\n [[2, 6],\n  [4, 8]]]"), ...
        "{B3}", "[[1, 2, 3]]", ...
        "{col_char}", "'ab'", ...
        "{[""a"", ""b""]}", "[""a"", ""b""]", ...
        "{[true false]}", "[true, false]", ...
        "{tbl}", strip(formattedDisplayText( ...
            tbl, LineSpacing="compact", SuppressMarkup=true, UseTrueFalseForLogical=true ...
        )) ...
    );

    keys = data.keys();

    for k = 1:length(keys)
        expr = keys(k);
        dval = data(expr);
        val  = fstr(expr);

        if verbose; fprintf("""%s"" -> ""%s"" ... ", expr, val); end

        if val~=dval
            fprintf("fstr(""%s"") gives ""%s"" rather than ""%s""\n", expr, val, dval);
            return
        end

        if verbose; fprintf("PASSED\n"); end
    end

    % lastwarn records a warning's identifier even while it is turned off
    warn_cases = { ...
        "{undefined_name}", "MMGA:fstr:evalFailed"; ...
        "{1:3}", "MMGA:fstr:badFormat"; ...
        "{c:.2f}", "MMGA:fstr:formatFailed"; ...
        ["a", "b"], "MMGA:fstr:notText" ...
    };
    old_state = warning("off", "all");
    restore = onCleanup(@() warning(old_state));
    for k = 1:height(warn_cases)
        lastwarn("");
        fstr(warn_cases{k, 1});
        [~, id] = lastwarn();

        if verbose; fprintf("warning %s ... ", warn_cases{k, 2}); end

        if id~=warn_cases{k, 2}
            fprintf("expected warning %s but got ""%s""\n", warn_cases{k, 2}, id);
            return
        end

        if verbose; fprintf("PASSED\n"); end
    end

    % bigr = rand(1000, 1000); %#ok<NASGU>
    % fstr("{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}" + ...
    %     "{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}{bigr}");

    pass = true;
end
